# Generated by Django 4.2.4 on 2023-08-17 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('viewCount', models.IntegerField(default=0)),
                ('likeCount', models.IntegerField(default=0)),
                ('playCount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=music.models.upload_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_music', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
