# Generated by Django 4.2.4 on 2023-08-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='music',
            name='audio_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
