# Generated by Django 4.2.4 on 2023-08-17 15:43

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_audio_file_music_audio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=music.models.upload_audio_file),
        ),
    ]
