# Generated by Django 4.2.4 on 2023-08-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_music_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
