# Generated by Django 4.2.4 on 2023-08-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_music_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='is_special_music',
            field=models.BooleanField(default=False),
        ),
    ]
