# Generated by Django 4.2.4 on 2023-08-22 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_music_created_at'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_and_dislike',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music'),
        ),
    ]
