# Generated by Django 4.2.4 on 2023-08-16 09:17

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_full_name_remove_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='block_status',
        ),
    ]
