# Generated by Django 4.2.4 on 2023-08-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_special_user',
            field=models.BooleanField(default=False, verbose_name='is special user'),
        ),
    ]
