# Generated by Django 4.2.4 on 2023-08-17 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام نمایشی')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='عنوان انگلیسی')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام نمایشی')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='عنوان انگلیسی')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('permissions', models.ManyToManyField(blank=True, related_name='role', to='acl.permission', verbose_name='نقش ها')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='acl.role', verbose_name='نقش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
